server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev_database
    username: mohirdev_jwt
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
